language: go

go:
  - 1.2
  - 1.3
  - tip

install:
  - go get -v code.google.com/p/go.tools/cmd/vet
  - go get -v github.com/golang/lint/golint
  - go get -d -t -v ./...
  - go build -v ./...

script:
  - go vet ./...
  - $HOME/gopath/bin/golint .
  - go test -v -parallel=8 ./...
