dist: bionic
language: go
services:
  - docker
go:
  - 1.13.x
install:
  - go get -v golang.org/x/lint/golint
  - go get -d -t -v ./...
  - go build -v ./...
jobs:
  include:
    - stage: Test
      script:
        - go vet ./...
        - $HOME/gopath/bin/golint -set_exit_status $(go list ./... | grep -v /vendor/)
        - go test -v ./...
    - stage: Fuzz regression
      script: ./fuzzit.sh local-regression
      # - stage: Fuzz
      #   if: branch = master AND type IN (push)
      #   script: ./fuzzit.sh fuzzing
